/**
 * Stable, machine-readable reason codes of the strategy engine.
 *
 * Specification:
 *   docs/trading/05-strategy-v1-specification.md ("Vorvalidierung",
 *   "Entry-Voraussetzungen", "Candidate-Preisplan", "Fehlende oder
 *   widersprüchliche Daten")
 *   docs/trading/03-domain-model.md (`TradeCandidate.strategyReasonCodes`,
 *   `invalidReasonCode`)
 *
 * These strings are persisted and consumed by the dashboard. They are
 * append-only: never rename, never reuse. Every refusal maps to exactly one
 * code — the engine makes no free-text decisions.
 */

export const StrategyReasonCode = {
  // ── Snapshot shape and versioning ───────────────────────────────────────
  SNAPSHOT_VERSION_UNSUPPORTED: "SNAPSHOT_VERSION_UNSUPPORTED",
  SNAPSHOT_VERSION_SUPPORTED: "SNAPSHOT_VERSION_SUPPORTED",
  SNAPSHOT_MALFORMED: "SNAPSHOT_MALFORMED",
  SNAPSHOT_TIMESTAMP_MALFORMED: "SNAPSHOT_TIMESTAMP_MALFORMED",
  SNAPSHOT_DECIMAL_MALFORMED: "SNAPSHOT_DECIMAL_MALFORMED",
  STRATEGY_KEY_UNKNOWN: "STRATEGY_KEY_UNKNOWN",
  STRATEGY_KEY_MISMATCH: "STRATEGY_KEY_MISMATCH",
  STRATEGY_VERSION_NOT_ACTIVE: "STRATEGY_VERSION_NOT_ACTIVE",
  STRATEGY_ENGINE_VERSION_MISMATCH: "STRATEGY_ENGINE_VERSION_MISMATCH",
  STRATEGY_SPECIFICATION_HASH_MISMATCH: "STRATEGY_SPECIFICATION_HASH_MISMATCH",
  STRATEGY_CODE_VERSION_MISSING: "STRATEGY_CODE_VERSION_MISSING",
  STRATEGY_VERSION_VALID: "STRATEGY_VERSION_VALID",

  // ── Assignment and scope ────────────────────────────────────────────────
  ASSIGNMENT_MISSING: "ASSIGNMENT_MISSING",
  ASSIGNMENT_DISABLED: "ASSIGNMENT_DISABLED",
  ASSIGNMENT_OUTSIDE_VALIDITY_WINDOW: "ASSIGNMENT_OUTSIDE_VALIDITY_WINDOW",
  ASSIGNMENT_TIMEFRAME_NOT_ALLOWED: "ASSIGNMENT_TIMEFRAME_NOT_ALLOWED",
  ASSIGNMENT_ACTIVE: "ASSIGNMENT_ACTIVE",

  ASSET_NOT_ALLOWED: "ASSET_NOT_ALLOWED",
  ASSET_NOT_CRYPTO: "ASSET_NOT_CRYPTO",
  ASSET_NOT_TRADABLE: "ASSET_NOT_TRADABLE",
  ASSET_NOT_ACTIVE: "ASSET_NOT_ACTIVE",
  ASSET_INSTRUMENT_STATUS_NOT_ACTIVE: "ASSET_INSTRUMENT_STATUS_NOT_ACTIVE",
  ASSET_QUOTE_CURRENCY_NOT_USDT: "ASSET_QUOTE_CURRENCY_NOT_USDT",
  ASSET_LEVERAGED_FORBIDDEN: "ASSET_LEVERAGED_FORBIDDEN",
  ASSET_INVERSE_FORBIDDEN: "ASSET_INVERSE_FORBIDDEN",
  ASSET_STABLECOIN_FORBIDDEN: "ASSET_STABLECOIN_FORBIDDEN",
  ASSET_SCOPE_VALID: "ASSET_SCOPE_VALID",

  EXECUTION_PROFILE_MISSING: "EXECUTION_PROFILE_MISSING",
  EXECUTION_PROFILE_NOT_ACTIVE: "EXECUTION_PROFILE_NOT_ACTIVE",
  EXECUTION_PROFILE_ACTIVE: "EXECUTION_PROFILE_ACTIVE",

  // ── Candle series integrity ─────────────────────────────────────────────
  CANDLES_MISSING: "CANDLES_MISSING",
  CANDLES_INSUFFICIENT_HISTORY: "CANDLES_INSUFFICIENT_HISTORY",
  CANDLE_NOT_CLOSED: "CANDLE_NOT_CLOSED",
  CANDLE_OPEN_TIME_DUPLICATE: "CANDLE_OPEN_TIME_DUPLICATE",
  CANDLE_SERIES_NOT_ASCENDING: "CANDLE_SERIES_NOT_ASCENDING",
  CANDLE_SERIES_GAP: "CANDLE_SERIES_GAP",
  CANDLE_INTERVAL_MISMATCH: "CANDLE_INTERVAL_MISMATCH",
  CANDLE_OHLC_INVARIANT_VIOLATED: "CANDLE_OHLC_INVARIANT_VIOLATED",
  CANDLE_VOLUME_NEGATIVE: "CANDLE_VOLUME_NEGATIVE",
  CANDLE_TIMESTAMP_AFTER_AS_OF: "CANDLE_TIMESTAMP_AFTER_AS_OF",
  CANDLE_SOURCE_UNKNOWN: "CANDLE_SOURCE_UNKNOWN",
  CANDLE_SERIES_VALID: "CANDLE_SERIES_VALID",

  // ── Freshness ───────────────────────────────────────────────────────────
  DATA_STALE_CANDLES_1H: "DATA_STALE_CANDLES_1H",
  DATA_STALE_CANDLES_4H: "DATA_STALE_CANDLES_4H",
  DATA_STALE_CANDLES_1D: "DATA_STALE_CANDLES_1D",
  DATA_STALE_DATA_QUALITY: "DATA_STALE_DATA_QUALITY",
  DATA_STALE_REGIME: "DATA_STALE_REGIME",
  DATA_STALE_SIGNAL_1H: "DATA_STALE_SIGNAL_1H",
  DATA_STALE_SIGNAL_4H: "DATA_STALE_SIGNAL_4H",
  DATA_STALE_SIGNAL_1D: "DATA_STALE_SIGNAL_1D",
  DATA_FRESHNESS_VALID: "DATA_FRESHNESS_VALID",

  // ── Data quality snapshot ───────────────────────────────────────────────
  DATA_QUALITY_MISSING: "DATA_QUALITY_MISSING",
  DATA_QUALITY_INSUFFICIENT: "DATA_QUALITY_INSUFFICIENT",
  DATA_QUALITY_PROVIDER_ERROR: "DATA_QUALITY_PROVIDER_ERROR",
  DATA_QUALITY_VALID: "DATA_QUALITY_VALID",

  // ── Referenced signals ──────────────────────────────────────────────────
  SIGNAL_MISSING_1H: "SIGNAL_MISSING_1H",
  SIGNAL_MISSING_4H: "SIGNAL_MISSING_4H",
  SIGNAL_MISSING_1D: "SIGNAL_MISSING_1D",
  SIGNAL_TIMESTAMP_AFTER_AS_OF: "SIGNAL_TIMESTAMP_AFTER_AS_OF",
  SIGNAL_NOT_ANCHORED_TO_CANDLE: "SIGNAL_NOT_ANCHORED_TO_CANDLE",
  SIGNAL_REFERENCES_VALID: "SIGNAL_REFERENCES_VALID",

  // ── Entry: trend, breakout, momentum, volatility, volume ────────────────
  TREND_FILTER_1H_FAILED: "TREND_FILTER_1H_FAILED",
  TREND_FILTER_4H_FAILED: "TREND_FILTER_4H_FAILED",
  TREND_FILTER_1D_FAILED: "TREND_FILTER_1D_FAILED",
  TREND_FILTER_1H_PASSED: "TREND_FILTER_1H_PASSED",
  TREND_FILTER_4H_PASSED: "TREND_FILTER_4H_PASSED",
  TREND_FILTER_1D_PASSED: "TREND_FILTER_1D_PASSED",
  TREND_INDICATOR_UNAVAILABLE: "TREND_INDICATOR_UNAVAILABLE",

  BREAKOUT_NOT_CONFIRMED: "BREAKOUT_NOT_CONFIRMED",
  BREAKOUT_CONFIRMED: "BREAKOUT_CONFIRMED",
  BREAKOUT_REFERENCE_UNAVAILABLE: "BREAKOUT_REFERENCE_UNAVAILABLE",
  // Short breakdown counterparts. Distinct codes rather than reusing the
  // breakout ones, so an operator reading a reason code always knows which
  // direction produced it (ADR 0011).
  BREAKDOWN_NOT_CONFIRMED: "BREAKDOWN_NOT_CONFIRMED",
  BREAKDOWN_CONFIRMED: "BREAKDOWN_CONFIRMED",
  BREAKDOWN_REFERENCE_UNAVAILABLE: "BREAKDOWN_REFERENCE_UNAVAILABLE",

  RSI_OUT_OF_RANGE: "RSI_OUT_OF_RANGE",
  RSI_IN_RANGE: "RSI_IN_RANGE",
  RSI_UNAVAILABLE: "RSI_UNAVAILABLE",

  RELATIVE_VOLUME_BELOW_MINIMUM: "RELATIVE_VOLUME_BELOW_MINIMUM",
  RELATIVE_VOLUME_CONFIRMED: "RELATIVE_VOLUME_CONFIRMED",
  RELATIVE_VOLUME_UNAVAILABLE: "RELATIVE_VOLUME_UNAVAILABLE",

  ATR_UNAVAILABLE: "ATR_UNAVAILABLE",
  ATR_RATIO_OUT_OF_RANGE: "ATR_RATIO_OUT_OF_RANGE",
  ATR_RATIO_IN_RANGE: "ATR_RATIO_IN_RANGE",

  // ── Entry: existing signal, multi-timeframe, regime, context ────────────
  SIGNAL_1H_DIRECTION_NOT_BULLISH: "SIGNAL_1H_DIRECTION_NOT_BULLISH",
  SIGNAL_1H_STATUS_NOT_ALLOWED: "SIGNAL_1H_STATUS_NOT_ALLOWED",
  SIGNAL_1H_SCORE_BELOW_MINIMUM: "SIGNAL_1H_SCORE_BELOW_MINIMUM",
  SIGNAL_1H_RISK_LEVEL_TOO_HIGH: "SIGNAL_1H_RISK_LEVEL_TOO_HIGH",
  SIGNAL_1H_CONFIRMED: "SIGNAL_1H_CONFIRMED",

  HIGHER_TIMEFRAME_4H_CONFLICT: "HIGHER_TIMEFRAME_4H_CONFLICT",
  HIGHER_TIMEFRAME_4H_CONFIRMED: "HIGHER_TIMEFRAME_4H_CONFIRMED",
  HIGHER_TIMEFRAME_1D_CONFLICT: "HIGHER_TIMEFRAME_1D_CONFLICT",
  HIGHER_TIMEFRAME_1D_CONFIRMED: "HIGHER_TIMEFRAME_1D_CONFIRMED",

  MTF_MISSING: "MTF_MISSING",
  MTF_SNAPSHOT_PRESENT: "MTF_SNAPSHOT_PRESENT",
  MTF_NOT_BULLISH_ALIGNED: "MTF_NOT_BULLISH_ALIGNED",
  MTF_ALIGNMENT_SCORE_BELOW_MINIMUM: "MTF_ALIGNMENT_SCORE_BELOW_MINIMUM",
  MTF_BULLISH_ALIGNED: "MTF_BULLISH_ALIGNED",

  REGIME_MISSING: "REGIME_MISSING",
  REGIME_NOT_RISK_ON: "REGIME_NOT_RISK_ON",
  REGIME_NOT_RISK_OFF: "REGIME_NOT_RISK_OFF",
  REGIME_RISK_MODE_BLOCKED: "REGIME_RISK_MODE_BLOCKED",
  REGIME_CONFIDENCE_BELOW_MINIMUM: "REGIME_CONFIDENCE_BELOW_MINIMUM",
  REGIME_RISK_ON: "REGIME_RISK_ON",
  REGIME_RISK_OFF: "REGIME_RISK_OFF",

  CONTEXT_CRITICAL_BEARISH_EVENT: "CONTEXT_CRITICAL_BEARISH_EVENT",
  CONTEXT_NO_BLOCKING_EVENT: "CONTEXT_NO_BLOCKING_EVENT",

  // ── Price plan ──────────────────────────────────────────────────────────
  STOP_DISTANCE_FLOOR_APPLIED: "STOP_DISTANCE_FLOOR_APPLIED",
  STOP_DISTANCE_ATR_APPLIED: "STOP_DISTANCE_ATR_APPLIED",
  STOP_DISTANCE_ABOVE_MAXIMUM: "STOP_DISTANCE_ABOVE_MAXIMUM",
  STOP_PRICE_NOT_POSITIVE: "STOP_PRICE_NOT_POSITIVE",
  REWARD_RISK_BELOW_MINIMUM: "REWARD_RISK_BELOW_MINIMUM",
  REWARD_RISK_CONFIRMED: "REWARD_RISK_CONFIRMED",
  PRICE_PLAN_VALID: "PRICE_PLAN_VALID",
  /** Direction-aware ordering guard refused the plan (trading-domain). */
  PRICE_PLAN_ORDER_INVALID: "PRICE_PLAN_ORDER_INVALID",

  // ── Candidate lifetime ──────────────────────────────────────────────────
  CANDIDATE_ALREADY_EXPIRED: "CANDIDATE_ALREADY_EXPIRED",
  CANDIDATE_WITHIN_VALIDITY_WINDOW: "CANDIDATE_WITHIN_VALIDITY_WINDOW",

  // ── Persistence-side outcomes (worker) ──────────────────────────────────
  CANDIDATE_CREATED: "CANDIDATE_CREATED",
  CANDIDATE_IDEMPOTENT_REPLAY: "CANDIDATE_IDEMPOTENT_REPLAY",
  CANDIDATE_INPUT_HASH_CONFLICT: "CANDIDATE_INPUT_HASH_CONFLICT"
} as const;
export type StrategyReasonCode =
  (typeof StrategyReasonCode)[keyof typeof StrategyReasonCode];

/** Every reason code, sorted — used by exhaustiveness and stability tests. */
export const ALL_STRATEGY_REASON_CODES: readonly StrategyReasonCode[] =
  Object.freeze(Object.values(StrategyReasonCode).sort());

/**
 * `INVALID_INPUT` covers formal and technical violations (docs/trading/05,
 * "Fehler 1–7 ergeben keinen Trade: bei formaler/technischer Verletzung
 * INVALID"). Every pre-validation stage refusal belongs here; a market that is
 * merely not tradable today yields `NO_CANDIDATE` instead.
 */
export const StrategyEvaluationOutcome = {
  CANDIDATE: "CANDIDATE",
  NO_CANDIDATE: "NO_CANDIDATE",
  INVALID_INPUT: "INVALID_INPUT"
} as const;
export type StrategyEvaluationOutcome =
  (typeof StrategyEvaluationOutcome)[keyof typeof StrategyEvaluationOutcome];

/** Which part of the pipeline produced a check result. */
export const StrategyCheckStage = {
  PRE_VALIDATION: "PRE_VALIDATION",
  ENTRY: "ENTRY",
  PRICE_PLAN: "PRICE_PLAN"
} as const;
export type StrategyCheckStage =
  (typeof StrategyCheckStage)[keyof typeof StrategyCheckStage];
