/**
 * Rule codes and stable reason codes of the risk engine.
 *
 * Specification: docs/trading/06-risk-engine-specification.md, "Regelkatalog"
 * (the 26 rows) and docs/trading/03-domain-model.md (`RiskRuleResult.ruleCode`,
 * `reasonCode`; `RiskAssessment.ruleSetVersion`).
 *
 * Both lists are persisted and consumed by the dashboard. They are append-only:
 * never rename a code, never reuse one for a different meaning.
 */

/** The 26 rules, in their mandatory evaluation and persistence order. */
export const RiskRuleCode = {
  SHADOW_MODE: "R-001-SHADOW-MODE",
  SESSION: "R-002-SESSION",
  PORTFOLIO_CONSISTENCY: "R-003-PORTFOLIO-CONSISTENCY",
  ASSET_SCOPE: "R-004-ASSET-SCOPE",
  LONG_ONLY: "R-005-LONG-ONLY",
  NO_LEVERAGE: "R-006-NO-LEVERAGE",
  STOP_REQUIRED: "R-007-STOP-REQUIRED",
  MIN_RR: "R-008-MIN-RR",
  RISK_PER_TRADE: "R-009-RISK-PER-TRADE",
  DAILY_LOSS: "R-010-DAILY-LOSS",
  OPEN_POSITIONS: "R-011-OPEN-POSITIONS",
  TRADES_PER_DAY: "R-012-TRADES-PER-DAY",
  GROSS_EXPOSURE: "R-013-GROSS-EXPOSURE",
  ASSET_EXPOSURE: "R-014-ASSET-EXPOSURE",
  CORRELATION: "R-015-CORRELATION",
  DATA_FRESHNESS: "R-016-DATA-FRESHNESS",
  DATA_QUALITY: "R-017-DATA-QUALITY",
  SPREAD: "R-018-SPREAD",
  SLIPPAGE: "R-019-SLIPPAGE",
  REGIME: "R-020-REGIME",
  LOSS_STREAK: "R-021-LOSS-STREAK",
  NO_SCALE_IN: "R-022-NO-SCALE-IN",
  NO_MARTINGALE: "R-023-NO-MARTINGALE",
  NO_POST_LOSS_INCREASE: "R-024-NO-POST-LOSS-INCREASE",
  INSTRUMENT_MINIMUMS: "R-025-INSTRUMENT-MINIMUMS",
  IDEMPOTENCY_VERSION: "R-026-IDEMPOTENCY-VERSION"
} as const;
export type RiskRuleCode = (typeof RiskRuleCode)[keyof typeof RiskRuleCode];

/** Evaluation order is part of the contract; the output preserves it exactly. */
export const RISK_RULE_ORDER: readonly RiskRuleCode[] = Object.freeze([
  RiskRuleCode.SHADOW_MODE,
  RiskRuleCode.SESSION,
  RiskRuleCode.PORTFOLIO_CONSISTENCY,
  RiskRuleCode.ASSET_SCOPE,
  RiskRuleCode.LONG_ONLY,
  RiskRuleCode.NO_LEVERAGE,
  RiskRuleCode.STOP_REQUIRED,
  RiskRuleCode.MIN_RR,
  RiskRuleCode.RISK_PER_TRADE,
  RiskRuleCode.DAILY_LOSS,
  RiskRuleCode.OPEN_POSITIONS,
  RiskRuleCode.TRADES_PER_DAY,
  RiskRuleCode.GROSS_EXPOSURE,
  RiskRuleCode.ASSET_EXPOSURE,
  RiskRuleCode.CORRELATION,
  RiskRuleCode.DATA_FRESHNESS,
  RiskRuleCode.DATA_QUALITY,
  RiskRuleCode.SPREAD,
  RiskRuleCode.SLIPPAGE,
  RiskRuleCode.REGIME,
  RiskRuleCode.LOSS_STREAK,
  RiskRuleCode.NO_SCALE_IN,
  RiskRuleCode.NO_MARTINGALE,
  RiskRuleCode.NO_POST_LOSS_INCREASE,
  RiskRuleCode.INSTRUMENT_MINIMUMS,
  RiskRuleCode.IDEMPOTENCY_VERSION
]);

export const RISK_RULE_COUNT = RISK_RULE_ORDER.length;

/**
 * Reason codes. The `*_OK` variants are written for passing rules too, because
 * docs/trading/03 requires every rule result — including PASS — to be stored.
 */
export const RiskReasonCode = {
  // ── Mode, session, portfolio ────────────────────────────────────────────
  SHADOW_MODE_OK: "SHADOW_MODE_OK",
  MODE_NOT_SHADOW: "MODE_NOT_SHADOW",
  CONFIG_INVALID: "CONFIG_INVALID",
  LIVE_TRADING_FORBIDDEN: "LIVE_TRADING_FORBIDDEN",
  BUILD_CAPABILITY_NOT_SHADOW_ONLY: "BUILD_CAPABILITY_NOT_SHADOW_ONLY",
  RISK_JOB_DISABLED: "RISK_JOB_DISABLED",

  SESSION_OK: "SESSION_OK",
  SESSION_BLOCKS_ENTRY: "SESSION_BLOCKS_ENTRY",
  SESSION_KILL_SWITCH_ENGAGED: "SESSION_KILL_SWITCH_ENGAGED",
  SESSION_RECONCILE_STALE: "SESSION_RECONCILE_STALE",
  SESSION_MISSING: "SESSION_MISSING",

  PORTFOLIO_CONSISTENT: "PORTFOLIO_CONSISTENT",
  PORTFOLIO_INCONSISTENT: "PORTFOLIO_INCONSISTENT",
  PORTFOLIO_NOT_ACTIVE: "PORTFOLIO_NOT_ACTIVE",
  PORTFOLIO_NEGATIVE_CASH: "PORTFOLIO_NEGATIVE_CASH",
  PORTFOLIO_ORPHAN_LEDGER_REFERENCE: "PORTFOLIO_ORPHAN_LEDGER_REFERENCE",
  PORTFOLIO_DUPLICATE_POSITION_SCOPE: "PORTFOLIO_DUPLICATE_POSITION_SCOPE",
  PORTFOLIO_RESERVATION_MISMATCH: "PORTFOLIO_RESERVATION_MISMATCH",

  // ── Instrument and direction ────────────────────────────────────────────
  ASSET_SCOPE_OK: "ASSET_SCOPE_OK",
  ASSET_NOT_ALLOWED: "ASSET_NOT_ALLOWED",
  NOT_SPOT_USDT: "NOT_SPOT_USDT",
  ASSIGNMENT_NOT_ACTIVE: "ASSIGNMENT_NOT_ACTIVE",

  LONG_ONLY_OK: "LONG_ONLY_OK",
  SIDE_NOT_ALLOWED: "SIDE_NOT_ALLOWED",

  NO_LEVERAGE_OK: "NO_LEVERAGE_OK",
  LEVERAGE_OR_MARGIN_FORBIDDEN: "LEVERAGE_OR_MARGIN_FORBIDDEN",

  // ── Price plan ──────────────────────────────────────────────────────────
  STOP_VALID: "STOP_VALID",
  STOP_MISSING_OR_INVALID: "STOP_MISSING_OR_INVALID",

  REWARD_RISK_OK: "REWARD_RISK_OK",
  REWARD_RISK_BELOW_MINIMUM: "REWARD_RISK_BELOW_MINIMUM",

  // ── Sizing and portfolio limits ─────────────────────────────────────────
  TRADE_RISK_WITHIN_LIMIT: "TRADE_RISK_WITHIN_LIMIT",
  TRADE_RISK_EXCEEDS_25BP: "TRADE_RISK_EXCEEDS_25BP",
  TRADE_RISK_NOT_COMPUTABLE: "TRADE_RISK_NOT_COMPUTABLE",
  EQUITY_NOT_POSITIVE: "EQUITY_NOT_POSITIVE",

  DAILY_LOSS_WITHIN_LIMIT: "DAILY_LOSS_WITHIN_LIMIT",
  DAILY_LOSS_LIMIT_REACHED: "DAILY_LOSS_LIMIT_REACHED",
  START_OF_DAY_SNAPSHOT_MISSING: "START_OF_DAY_SNAPSHOT_MISSING",

  OPEN_POSITIONS_WITHIN_LIMIT: "OPEN_POSITIONS_WITHIN_LIMIT",
  MAX_OPEN_POSITIONS: "MAX_OPEN_POSITIONS",

  DAILY_TRADES_WITHIN_LIMIT: "DAILY_TRADES_WITHIN_LIMIT",
  MAX_DAILY_TRADES: "MAX_DAILY_TRADES",

  GROSS_EXPOSURE_WITHIN_LIMIT: "GROSS_EXPOSURE_WITHIN_LIMIT",
  MAX_GROSS_EXPOSURE: "MAX_GROSS_EXPOSURE",

  ASSET_EXPOSURE_WITHIN_LIMIT: "ASSET_EXPOSURE_WITHIN_LIMIT",
  MAX_ASSET_EXPOSURE: "MAX_ASSET_EXPOSURE",
  DUPLICATE_ASSET_POSITION: "DUPLICATE_ASSET_POSITION",

  CORRELATED_EXPOSURE_WITHIN_LIMIT: "CORRELATED_EXPOSURE_WITHIN_LIMIT",
  MAX_CORRELATED_EXPOSURE: "MAX_CORRELATED_EXPOSURE",
  CORRELATION_GROUP_MISSING: "CORRELATION_GROUP_MISSING",

  // ── Data ────────────────────────────────────────────────────────────────
  DATA_FRESH: "DATA_FRESH",
  DATA_STALE_CANDLES_1H: "DATA_STALE_CANDLES_1H",
  DATA_STALE_CANDLES_4H: "DATA_STALE_CANDLES_4H",
  DATA_STALE_CANDLES_1D: "DATA_STALE_CANDLES_1D",
  DATA_STALE_DATA_QUALITY: "DATA_STALE_DATA_QUALITY",
  DATA_STALE_REGIME: "DATA_STALE_REGIME",
  DATA_STALE_PORTFOLIO_SNAPSHOT: "DATA_STALE_PORTFOLIO_SNAPSHOT",
  DATA_TIMESTAMP_IN_FUTURE: "DATA_TIMESTAMP_IN_FUTURE",
  CANDIDATE_EXPIRED: "CANDIDATE_EXPIRED",
  CANDIDATE_NOT_READY: "CANDIDATE_NOT_READY",

  DATA_QUALITY_OK: "DATA_QUALITY_OK",
  DATA_QUALITY_INSUFFICIENT: "DATA_QUALITY_INSUFFICIENT",
  DATA_QUALITY_CONTRADICTORY: "DATA_QUALITY_CONTRADICTORY",

  // ── Execution profile ───────────────────────────────────────────────────
  SPREAD_WITHIN_LIMIT: "SPREAD_WITHIN_LIMIT",
  SPREAD_LIMIT_EXCEEDED: "SPREAD_LIMIT_EXCEEDED",
  EXECUTION_PROFILE_MISSING: "EXECUTION_PROFILE_MISSING",
  EXECUTION_PROFILE_NOT_ACTIVE: "EXECUTION_PROFILE_NOT_ACTIVE",
  EXECUTION_PROFILE_INVALID: "EXECUTION_PROFILE_INVALID",

  SLIPPAGE_WITHIN_LIMIT: "SLIPPAGE_WITHIN_LIMIT",
  SLIPPAGE_LIMIT_EXCEEDED: "SLIPPAGE_LIMIT_EXCEEDED",
  SLIPPAGE_NOT_PRICED_IN: "SLIPPAGE_NOT_PRICED_IN",

  // ── Regime and streaks ──────────────────────────────────────────────────
  REGIME_OK: "REGIME_OK",
  MARKET_REGIME_CONFLICT: "MARKET_REGIME_CONFLICT",
  REGIME_MISSING: "REGIME_MISSING",

  LOSS_STREAK_WITHIN_LIMIT: "LOSS_STREAK_WITHIN_LIMIT",
  CONSECUTIVE_LOSS_LIMIT: "CONSECUTIVE_LOSS_LIMIT",

  // ── Structural prohibitions ─────────────────────────────────────────────
  NO_SCALE_IN_OK: "NO_SCALE_IN_OK",
  AVERAGING_OR_SCALE_IN_FORBIDDEN: "AVERAGING_OR_SCALE_IN_FORBIDDEN",

  DETERMINISTIC_SIZE_OK: "DETERMINISTIC_SIZE_OK",
  NON_DETERMINISTIC_SIZE_OVERRIDE: "NON_DETERMINISTIC_SIZE_OVERRIDE",

  RISK_NOT_INCREASED_AFTER_LOSS: "RISK_NOT_INCREASED_AFTER_LOSS",
  RISK_INCREASE_AFTER_LOSS: "RISK_INCREASE_AFTER_LOSS",

  // ── Instrument minimums ─────────────────────────────────────────────────
  INSTRUMENT_MINIMUMS_OK: "INSTRUMENT_MINIMUMS_OK",
  BELOW_INSTRUMENT_MINIMUM: "BELOW_INSTRUMENT_MINIMUM",
  QUANTITY_NOT_POSITIVE: "QUANTITY_NOT_POSITIVE",
  INSUFFICIENT_CASH: "INSUFFICIENT_CASH",
  QUANTITY_ABOVE_INSTRUMENT_MAXIMUM: "QUANTITY_ABOVE_INSTRUMENT_MAXIMUM",

  // ── Idempotency and versions ────────────────────────────────────────────
  VERSIONS_CONSISTENT: "VERSIONS_CONSISTENT",
  IDEMPOTENCY_OR_VERSION_CONFLICT: "IDEMPOTENCY_OR_VERSION_CONFLICT",
  STRATEGY_VERSION_RETIRED: "STRATEGY_VERSION_RETIRED",
  RISK_LIMIT_SET_NOT_ACTIVE: "RISK_LIMIT_SET_NOT_ACTIVE",
  CANDIDATE_PLAN_INCOMPLETE: "CANDIDATE_PLAN_INCOMPLETE",
  CANDIDATE_ALREADY_DECIDED: "CANDIDATE_ALREADY_DECIDED",

  // ── Overall verdict ─────────────────────────────────────────────────────
  RISK_APPROVED: "RISK_APPROVED",

  // ── Snapshot shape ──────────────────────────────────────────────────────
  RISK_SNAPSHOT_VERSION_UNSUPPORTED: "RISK_SNAPSHOT_VERSION_UNSUPPORTED",
  RISK_SNAPSHOT_MALFORMED: "RISK_SNAPSHOT_MALFORMED"
} as const;
export type RiskReasonCode = (typeof RiskReasonCode)[keyof typeof RiskReasonCode];

export const ALL_RISK_REASON_CODES: readonly RiskReasonCode[] = Object.freeze(
  Object.values(RiskReasonCode).sort()
);

/** Overall verdict of one assessment. Maps to `RiskAssessmentStatus` on write. */
export const RiskEvaluationOutcome = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  ERROR: "ERROR"
} as const;
export type RiskEvaluationOutcome =
  (typeof RiskEvaluationOutcome)[keyof typeof RiskEvaluationOutcome];
